### ISSUE TITLE
access to relative paths

### ISSUE THREAD

**Issue by jeromew** [d3/d3-path#13]
Hello,

this module builds SVG paths using absolute commands (M, Z, H, V, ..).

would it make sense for d3  to have an API to be able to build relative paths using (m, z, h, v, ..) ?

I am currently using both `d3-path` which has a nice `arc` API and https://www.npmjs.com/package/svg-path-generator which has a `relative()` facility and trying to see how to go forward to have a unified path generator.

my need for relatives path does not really come out of d3 so I would understand if the design goals of `d3-path` do not emcompass this feature. I am trying to generate shape paths for a laser cutter and it is easier to reason about with relative positions.

**Comment by mbostock** [comment]
I don’t think generating relative paths is in-scope for this library; it’s purpose is to implement the [CanvasPathMethods API](https://www.w3.org/TR/2dcontext/#canvaspathmethods) for serializing to SVG. You could always fork the library to generate relative paths instead, though. Sorry!
