### ISSUE TITLE
Arc and arcTo draw only circular arcs.

### ISSUE THREAD

**Issue by rybaczewa** [d3/d3-path#18]
Currently, neiher `path.arc` nor `path.arcTo` allow to draw elliptical arcs - only circular. Single radius is passed and used for both `rx` and `ry` [parameters](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/d#Elliptical_Arc_Curve).

https://github.com/d3/d3-path/blob/fb809cd12e1122ed2fd6df72d2017592f1dc4451/src/path.js#L118-L120

It's possible to draw first, but not the second arc:
https://jsfiddle.net/qd1ph9y0/5/

**Comment by mbostock** [comment]
Correct. Please see the CanvasPathMethods specification:

https://www.w3.org/TR/2dcontext/#building-paths

**Comment by carpiediem** [comment]
Would it make sense to add an additional method that captures the capabilities of [the SVG elliptical arc command](https://www.w3.org/TR/SVG/paths.html#PathDataEllipticalArcCommands)?

**Comment by mbostock** [comment]
No. This interface is specified by the CanvasPathMethods API.
