### ISSUE TITLE
Drop redundant L in arc commands.

### ISSUE THREAD

**Issue by mbostock** [d3/d3-path#3]
We’re always drawing the straight line, even if it’s not needed.

**Comment by twilliamsgsnetx** [comment]
So is this what is causing there to be no L in my generated arcs? Migrating my code to v4, and noticing my technique to pull the path apart and determine x,y coordinates of end of the path no longer works, because there is no L command within.

**Comment by mbostock** [comment]
If you want to parse SVG path data, you should to refer to the [SVG specification](https://www.w3.org/TR/SVG/paths.html#PathData). You can also use the SVGPathElement’s [getPathSegAtLength](https://www.w3.org/TR/SVG/paths.html#__svg__SVGPathElement__getPathSegAtLength) at method to have the browser parse the string for you.
