### ISSUE TITLE
Replace concat string with join

### ISSUE THREAD

**Issue by lpatiny** [d3/d3-path#40]
I would like to change the code of path that would create internally an array of string and then return the string[].join at the end.

Concatenating string is a huge overhead and I expect a large speed improvement with this approach based on my experience with www.nmrium.org

WDYT ?

**Comment by Fil** [comment]
That could be interesting. We're always looking for better performance.

**Comment by curran** [comment]
I suppose the first step would be to benchmark the performance before the change.

**Comment by lpatiny** [comment]
I created a benchmark here: https://jsbench.me/9jm4gsw0uj/1

In short the concat approach seems the fastest currently so no change to do. 

The results on my macbook pro M4 are:

![image](https://github.com/user-attachments/assets/7b44b7b6-3bac-498b-a29a-7360b91a4d72)
